baseURL = "https://www.christmasgoodies.in/"

enableRobotsTXT = true
canonifyURLs = true

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

defaultContentLanguage = "en"

# The name of this wonderful theme ;-).
theme = "hugo-scroll"

# The "title" of your website
title = "Christmas Goodies"

[params]
# A "copyright"-line to be added at the bottom of the page.
# Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
copyright = "© Glen Mascarenhas 2023"

# The "description" of your website. This is used in the meta data of your generated html.
description = "Spread the Holiday Cheer with our Christmas goodies for friends and family"

# The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
favicon = "images/favicon.png"

# These "images" are used for the structured data templates. This will show up, when
# services like Twitter or Slack want to generate a preview of a link to your site.
# See https://gohugo.io/templates/internal#twitter-cards and
# https://gohugo.io/templates/internal#open-graph.
images = ["images/preview.webp"]

# Another "title" :-). This one is used as the site_name on the Hugo's internal
# opengraph structured data template.
# See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
title = "Trendy Christmas Goodies"

# This theme will, by default, inject a design-by-line at the bottom of the page.
# You can turn it off, but we would really appreciate if you don’t :-)
# hidedesignbyline = true

[params.meta]
keywords = "christmas, goodies, gifts, santa, holiday, gifting, cheer, holly, stocking, gift, snowflake, trendy, cups, coasters, towels, hampers"

